name: attendify
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^2.0.0
  flutter_native_splash: ^2.2.19
  intl: ^0.17.0
  date_time_picker: ^2.0.1
  flutter_datetime_picker: ^1.5.0
  url_launcher: ^6.1.11
  

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splashlogo-Attendify.png
  android: true
  ios: true
  web: true

flutter: 
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/background/
  
